# Generated by Django 6.0.1 on 2026-02-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('userid', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
